name: MongoDB Atlas Query Workflow

on:
  push:
    branches:
      - main

jobs:
  execute-query:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Get Runner's Public IP
      - name: Get Runner IP
        id: get-ip
        run: echo "RUNNER_IP=$(curl -s https://checkip.amazonaws.com)" >> $GITHUB_ENV

      # Step 3: Add GitHub Runner IP to MongoDB Atlas
      - name: Add IP to MongoDB Atlas
        uses: mongodb/atlas-github-action@v0.2.0
        with:
          publicApiKey: ${{ secrets.PUBLIC_API_KEY }}
          privateApiKey: ${{ secrets.PRIVATE_API_KEY }}
          projectId: ${{ secrets.PROJECT_ID }}
          allowListEntry: ${{ env.RUNNER_IP }}

      # Step 4: Setup MongoDB Shell
      - name: Setup MongoDB Tools
        uses: boly38/action-mongo-tools@stable
        with:
          mongo-shell: "true"
          mongo-tools: "false"

      # Step 5: Execute Query from File
      - name: Execute Query from File
        run: |
          mongosh --tls --tlsAllowInvalidCertificates "${{ secrets.MONGO_URI }}" query.js

      # Step 6: Remove IP from MongoDB Atlas
      - name: Remove IP from MongoDB Atlas
        if: always()
        uses: mongodb/atlas-github-action@v0.2.0
        with:
          publicApiKey: ${{ secrets.PUBLIC_API_KEY }}
          privateApiKey: ${{ secrets.PRIVATE_API_KEY }}
          projectId: ${{ secrets.PROJECT_ID }}
          deleteAllowListEntry: ${{ env.RUNNER_IP }}
