name: MongoDB Atlas Query Workflow

on:
  push:
    branches:
      - main

jobs:
  execute-query:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Get the runner's public IP
      - name: Get Runner IP
        id: ip
        run: |
          RUNNER_IP=$(curl -s https://api.ipify.org)
          echo "RUNNER_IP=$RUNNER_IP" >> $GITHUB_ENV
          echo "Detected Runner IP: $RUNNER_IP"

      # Step 3: Add runner IP to MongoDB Atlas Access List
      - name: Add Runner IP to MongoDB Atlas Access List
        id: add-ip
        uses: mongodb/atlas-github-action@v0.2.0
        with:
          publicApiKey: ${{ secrets.PUBLIC_API_KEY }}
          privateApiKey: ${{ secrets.PRIVATE_API_KEY }}
          projectId: ${{ secrets.PROJECT_ID }}
          action: "addIpToAccessList"
          ipAddress: ${{ env.RUNNER_IP }}
          comment: "Temporary GitHub Actions Runner IP"
        continue-on-error: false  # Fail if this step fails

      # Step 4: Verify IP was added
      - name: Verify IP in Access List
        run: |
          echo "Checking if ${{ env.RUNNER_IP }} was added to the access list..."
          ACCESS_LIST=$(curl -s -u "${{ secrets.PUBLIC_API_KEY }}:${{ secrets.PRIVATE_API_KEY }}" \
            --digest "https://cloud.mongodb.com/api/atlas/v1.0/groups/${{ secrets.PROJECT_ID }}/accessList" | jq -r '.results[] | .ipAddress')
          echo "Current access list IPs: $ACCESS_LIST"
          if echo "$ACCESS_LIST" | grep -q "${{ env.RUNNER_IP }}"; then
            echo "IP ${{ env.RUNNER_IP }} successfully added!"
          else
            echo "Error: IP ${{ env.RUNNER_IP }} not found in access list!"
            exit 1
          fi

      # Step 5: Wait for IP access list to propagate
      - name: Wait for Network Update
        run: |
          echo "Waiting 30 seconds for IP access list to update..."
          sleep 30

      # Step 6: Set up MongoDB shell
      - name: Setup MongoDB Tools
        uses: boly38/action-mongo-tools@stable
        with:
          mongo-shell: "true"
          mongo-tools: "false"

      # Step 7: Test connectivity and execute query
      - name: Execute Query from File
        run: |
          echo "Attempting to connect to MongoDB Atlas..."
          mongosh "${{ secrets.MONGO_URI }}" --eval "print('Connected successfully')" || exit 1
          echo "Running query.js..."
          mongosh "${{ secrets.MONGO_URI }}" query.js

      # Step 8: Remove Runner IP from Access List (cleanup)
      - name: Remove Runner IP from MongoDB Atlas Access List
        if: always()
        uses: mongodb/atlas-github-action@v0.2.0
        with:
          publicApiKey: ${{ secrets.PUBLIC_API_KEY }}
          privateApiKey: ${{ secrets.PRIVATE_API_KEY }}
          projectId: ${{ secrets.PROJECT_ID }}
          action: "removeIpFromAccessList"
          ipAddress: ${{ env.RUNNER_IP }}
