name: MongoDB Atlas Query Workflow

on:
  push:
    branches:
      - main

jobs:
  execute-query:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Atlas CLI
        uses: andreaangiolillo/atlas-cli-github-action@v1.1.0
        with:
          public-key: ${{ secrets.PUBLIC_API_KEY }}
          private-key: ${{ secrets.PRIVATE_API_KEY }}
          org-id: ${{ secrets.ORG_ID }}        
          project-id: ${{ secrets.PROJECT_ID }} 
  
      - name: Setup mongo tools - only shell
        uses: boly38/action-mongo-tools@stable
        with:
          mongo-shell: "true"
          mongo-tools: "false"

      - name: Execute Query from File
        run: |
          mongosh "${{ secrets.MONGO_URI }}" query.js

    
