name: MongoDB Atlas Query Workflow

on:
  push:
    branches:
      - main

jobs:
  execute-query:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up MongoDB Atlas CLI
      - name: Setup MongoDB Atlas CLI
        uses: mongodb/atlas-github-action@v0.2.0
        
      # Step 3: Authenticate with MongoDB Atlas
      - name: Authenticate with Atlas
        run: |
          atlas config init --publicApiKey "${{ secrets.PUBLIC_API_KEY }}" --privateApiKey "${{ secrets.PRIVATE_API_KEY }}"


      # Step 3: Retrieve Cluster Connection String
      - name: Retrieve Cluster Connection String
        id: get-connection
        run: |
          CONNECTION_STRING=$(atlas clusters connectionStrings describe "test-cluster-git" --projectId ${{ secrets.PROJECT_ID }} --output json | grep -o '"standardSrv": *"[^"]*' | grep -o '[^"]*$')
          echo "connection_string=$CONNECTION_STRING" >> $GITHUB_ENV

      # Step 4: Install MongoDB Shell (mongosh)
      - name: Install MongoDB Shell
        run: |
          sudo apt update && sudo apt install -y mongodb-mongosh

      # Step 5: Execute Query from File
      - name: Execute Query from File
        run: |
          mongosh "$connection_string/test_collection?authSource=admin" query.js
