name: MongoDB Atlas Query Workflow

on:
  push:
    branches:
      - main

jobs:
  execute-query:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Runner IP
        id: get-ip
        run: |
           echo "RUNNER_IP=$(curl -s https://checkip.amazonaws.com | tr -d '\n')" >> $GITHUB_ENV
           echo "Runner IP: $RUNNER_IP"
           shell: bash

      - name: Add Runner IP to MongoDB Atlas Access List
        run: |
          AUTH_HEADER="Authorization: Basic $(echo -n '${{ secrets.PUBLIC_API_KEY }}:${{ secrets.PRIVATE_API_KEY }}' | base64)"
          curl -X POST "https://cloud.mongodb.com/api/atlas/v1.0/groups/${{ secrets.PROJECT_ID }}/accessList" \
            --header "Content-Type: application/json" \
            --header "Accept: application/json" \
            --header "$AUTH_HEADER" \
            --data '{"ipAddress":"'"$RUNNER_IP"'","comment":"GitHub Actions Runner"}'

      - name: Setup MongoDB Tools
        uses: boly38/action-mongo-tools@stable
        with:
          mongo-shell: "true"
          mongo-tools: "false"

      - name: Execute Query from File
        run: |
          mongosh "${{ secrets.MONGO_URI }}" query.js

      - name: Remove Runner IP from MongoDB Atlas Access List
        if: always()
        run: |
          AUTH_HEADER="Authorization: Basic $(echo -n '${{ secrets.PUBLIC_API_KEY }}:${{ secrets.PRIVATE_API_KEY }}' | base64)"
          curl -X DELETE "https://cloud.mongodb.com/api/atlas/v1.0/groups/${{ secrets.PROJECT_ID }}/accessList/${RUNNER_IP}" \
            --header "Accept: application/json" \
            --header "$AUTH_HEADER"
