name: MongoDB Atlas Query Workflow

on:
  push:
    branches:
      - main

jobs:
  execute-query:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Get the GitHub Runner's Public IP
      - name: Get Runner Public IP
        id: get-ip
        run: |
          echo "RUNNER_IP=$(curl -s https://checkip.amazonaws.com | tr -d '\n')" >> $GITHUB_ENV
          echo "Runner IP: $RUNNER_IP"

      # Step 3: Add Runner IP to MongoDB Atlas Access List
      - name: Add Runner IP to MongoDB Atlas Access List
        run: |
          curl -X POST "https://cloud.mongodb.com/api/atlas/v1.0/groups/${{ secrets.PROJECT_ID }}/accessList" \
            --hea
