name: MongoDB Atlas CI/CD

on:
  push:
    branches:
      - main

jobs:
  mongodb:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Authenticate with MongoDB Atlas using GitHub Actions module
      - name: Authenticate with MongoDB Atlas
        uses: mongodb/atlas-github-action@v0.2.0
        with:
          publicApiKey: ${{ secrets.PUBLIC_API_KEY }}
          privateApiKey: ${{ secrets.PRIVATE_API_KEY }}
          projectId: ${{ secrets.PROJECT_ID }}

       c

      # Step 4: Test connection and create database
      - name: Run MongoDB Commands
        run: |
         mongosh "${{ secrets.MONGO_URI }}" --eval "
         db = db.getSiblingDB('github_test');
         db.test_collection.insertOne({name: 'GitHub Actions Test'});
         "



     
         


          
