name: MongoDB CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  mongodb_operations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate and Run MongoDB Commands
        uses: mongodb-js/mongosh-action@v1
        with:
          connection-string: "mongodb+srv://kumaranimesh462:qbj29ybnliUMmpCL@test-cluster-git.nydov.mongodb.net/?retryWrites=true&w=majority&appName=test-cluster-git"
          # connection-string: "mongodb+srv://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PASS }}@${{ secrets.MONGO_URI }}/?retryWrites=true&w=majority"
          script: |
            use my_database;
            db.my_collection.insertOne({ name: "Animesh", role: "DevOps Engineer" });
            printjson(db.my_collection.findOne());
