name: MongoDB Atlas CI/CD

on:
  push:
    branches:
      - main

jobs:
  mongodb_atlas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: MongoDB Atlas Action
        uses: mongodb/atlas-github-action@v0.2.0
        with:
          publicApiKey: ${{ secrets.ATLAS_PUBLIC_KEY }}
          privateApiKey: ${{ secrets.ATLAS_PRIVATE_KEY }}
          projectId: ${{ secrets.ATLAS_PROJECT_ID }}
          clusterName: "test-cluster-git"
          orgId: "" # Optional

      - name: Run MongoDB Commands
        run: |
          mongosh "mongodb+srv://kumaranimesh462:qbj29ybnliUMmpCL@test-cluster-git.nydov.mongodb.net/?retryWrites=true&w=majority&appName=test-cluster-git" --eval '
            use my_database;
            db.my_collection.insertOne({ name: "Animesh", role: "DevOps Engineer" });
            printjson(db.my_collection.findOne());
          '
