name: MongoDB Atlas Query Workflow

on:
  push:
    branches:
      - main

jobs:
  execute-query:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Get GitHub Actions Runner IP
      - name: Get GitHub Runner IP
        id: get_ip
        run: |
          echo "RUNNER_IP=$(curl -s https://checkip.amazonaws.com | tr -d '\n')" >> "$GITHUB_ENV"

      # Step 3: Setup MongoDB Atlas CLI
      - name: Setup MongoDB Atlas CLI
        uses: mongodb/atlas-github-action@v0.2.0

      # Step 4: Configure API Key for MongoDB CLI (Fix authentication issue)
      - name: Configure MongoDB Atlas CLI with API Key
        run: |
          atlas config set public_api_key "${{ secrets.PUBLIC_API_KEY }}"
          atlas config set private_api_key "${{ secrets.PRIVATE_API_KEY }}"

      # Step 5: Add GitHub Runner IP to MongoDB Atlas Access List
      - name: Add Runner IP to MongoDB Atlas Access List
        run: |
          atlas accessLists create $RUNNER_IP \
            --type ipAddress \
            --projectId "${{ secrets.PROJECT_ID }}" \
            --comment "Temporary access for GitHub Actions Runner"

      # Step 6: Setup MongoDB Tools
      - name: Setup MongoDB Tools
        uses: boly38/action-mongo-tools@stable
        with:
          mongo-shell: "true"
          mongo-tools: "false"

      # Step 7: Execute Query from File
      - name: Execute Query from File
        run: |
          mongosh "${{ secrets.MONGO_URI }}" query.js

      # Step 8: Remove GitHub Runner IP from Access List (Cleanup)
      - name: Remove Runner IP from MongoDB Atlas Access List
        if: always()
        run: |
          atlas accessLists delete $RUN
