name: Deploy MongoDB Query to Atlas

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get the public IP of this runner
        id: get_gh_runner_ip
        shell: bash
        run: |
          echo "ip_address=$(curl -s https://checkip.amazonaws.com | tr -d '\n')" >> "$GITHUB_OUTPUT"


      - name: Add runner IP to MongoDB Atlas access list
        run: |
          atlas accessLists create ${{ steps.get_gh_runner_ip.outputs.ip_address }} \
            --type ipAddress \
            --projectId "${{ secrets.PROJECT_ID }}" \
            --comment "Temporary access for GitHub Actions Runner"

      - name: Setup MongoDB Tools
        uses: boly38/action-mongo-tools@stable
        with:
          mongo-shell: "true"
          mongo-tools: "false"

      - name: Execute Query from File
        run: |
          mongosh "${{ secrets.MONGO_URI }}" query.js

      - name: Remove GitHub Runner IP from MongoDB Atlas
        if: always()
        uses: mongodb/atlas-github-action@v0.2.0
        with:
          publicApiKey: ${{ secrets.PUBLIC_API_KEY }}
          privateApiKey: ${{ secrets.PRIVATE_API_KEY }}
          projectId: ${{ secrets.PROJECT_ID }}
          deleteIps: ${{ env.RUNNER_IP }}
