name: MongoDB Atlas Query Workflow

on:
  push:
    branches:
      - main

jobs:
  execute-query:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MongoDB Atlas CLI
        uses: mongodb/atlas-github-action@v0.2.0
         
      - name: Authenticate with Atlas
        run: |
          atlas config set public_api_key "${{ secrets.PUBLIC_API_KEY }}"
          atlas config set private_api_key "${{ secrets.PRIVATE_API_KEY }}"
          atlas config set org_id "${{ secrets.ORG_ID }}"
          atlas config set project_id "${{ secrets.PROJECT_ID }}"
  
      - name: Setup mongo tools - only shell
        uses: boly38/action-mongo-tools@stable
        with:
          mongo-shell: "true"
          mongo-tools: "false"

      - name: Execute Query from File
        run: |
          mongosh "${{ secrets.MONGO_URI }}" query.js

    
