name: MongoDB Atlas CI/CD

on: [push]

jobs:
  mongodb:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Authenticate with MongoDB Atlas using GitHub Actions module
      - name: Authenticate with MongoDB Atlas
        uses: mongodb/atlas-github-action@v0.2.0
        with:
          publicApiKey: ${{ secrets.PUBLIC_API_KEY }}
          privateApiKey: ${{ secrets.PRIVATE_API_KEY }}
          projectId: ${{ secrets.PROJECT_ID }}

       # ✅ Step 3: Install MongoDB Shell (mongosh)
      - name: Install MongoDB Shell
        run: |
          curl -fsSL https://www.mongodb.org/static/pgp/server-6.0.asc | sudo tee /usr/share/keyrings/mongodb-server-key.asc
          echo "deb [signed-by=/usr/share/keyrings/mongodb-server-key.asc] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt update
          sudo apt install -y mongodb-mongosh

      # ✅ Step 4: Test connection and create database
      - name: Run MongoDB Commands
        run: |
         mongosh "${{ secrets.MONGO_URI }}" --eval "
         use github_test_db;
         db.test_collection.insertOne({name: 'GitHub Actions Test', createdAt: new Date()});
         "



     
         


          
