name: MongoDB Atlas Query Workflow
on:
  push:
    branches:
      - main
jobs:
  execute-query:
    runs-on: ubuntu-latest
    
    env:
      MONGODB_URI: ${{ secrets.MONGO_URI }}
      PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
      PRIVATE_API_KEY: ${{ secrets.PRIVATE_API_KEY }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      # Step 2: Get the current runner IP
      - name: Get Runner IP
        id: get-ip
        run: echo "RUNNER_IP=$(curl -s https://api.ipify.org)" >> $GITHUB_ENV
        
      # Step 3: Add Runner IP to Atlas Network Access using MongoDB Atlas GitHub Action
      - name: Add IP to MongoDB Atlas Network Access
        uses: mongodb-labs/atlas-github-action@v1
        with:
          action: 'add-ip'
          project_id: ${{ env.PROJECT_ID }}
          api_public_key: ${{ env.PUBLIC_API_KEY }}
          api_private_key: ${{ env.PRIVATE_API_KEY }}
          ip_address: ${{ env.RUNNER_IP }}
          comment: 'GitHub Actions Runner - Temporary'
          cidr_block: 32
          
      # Step 4: Setup MongoDB Tools
      - name: Setup MongoDB Tools
        uses: boly38/action-mongo-tools@stable
        with:
          mongo-shell: "true"
          mongo-tools: "false"
          
      # Step 5: Execute Query from File
      - name: Execute Query from File
        run: mongosh "$MONGODB_URI" query.js
        
      # Step 6: Clean up - Remove IP from Atlas Network Access using MongoDB Atlas GitHub Action
      - name: Remove IP from MongoDB Atlas Network Access
        if: always()
        uses: mongodb-labs/atlas-github-action@v1
        with:
          action: 'delete-ip'
          project_id: ${{ env.PROJECT_ID }}
          api_public_key: ${{ env.PUBLIC_API_KEY }}
          api_private_key: ${{ env.PRIVATE_API_KEY }}
          ip_address: ${{ env.RUNNER_IP }}
          cidr_block: 32
