name: Deploy MongoDB Query to Atlas

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get GitHub Runner IP
      id: get_ip
      run: |
        echo "RUNNER_IP=$(curl -s ifconfig.me)" >> $GITHUB_ENV
        echo "Runner IP: $RUNNER_IP"

    - name: Add GitHub Runner IP to MongoDB Atlas
      uses: mongodb/atlas-github-action@v0.2.0
      with:
        publicApiKey: ${{ secrets.MONGO_ATLAS_PUBLIC_KEY }}
        privateApiKey: ${{ secrets.MONGO_ATLAS_PRIVATE_KEY }}
        projectId: ${{ secrets.MONGO_ATLAS_PROJECT_ID }}
        allowIps: ${{ env.RUNNER_IP }}

    - name: Execute MongoDB Query
      uses: boly38/action-mongo-tools@stable
      with:
        uri: ${{ secrets.MONGO_URI }}
        database: test_collection  # Change to your database name
        script: ./query.js    # Ensure your query is written in this file

    - name: Remove GitHub Runner IP from MongoDB Atlas
      if: always()
      uses: mongodb/atlas-github-action@v0.2.0
      with:
        publicApiKey: ${{ secrets.MONGO_ATLAS_PUBLIC_KEY }}
        privateApiKey: ${{ secrets.MONGO_ATLAS_PRIVATE_KEY }}
        projectId: ${{ secrets.MONGO_ATLAS_PROJECT_ID }}
        deleteIps: ${{ env.RUNNER_IP }}
