name: MongoDB Atlas Query Workflow

on:
  push:
    branches:
      - main

jobs:
  execute-query:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up MongoDB Atlas CLI with official action
      - name: Setup Atlas CLI
        uses: mongodb/atlas-github-action@v0.2.0
        env:
          MONGODB_ATLAS_PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
          MONGODB_ATLAS_PRIVATE_API_KEY: ${{ secrets.PRIVATE_API_KEY }}
          MONGODB_ATLAS_ORG_ID: ${{ secrets.ORG_ID }}
          MONGODB_ATLAS_PROJECT_ID: ${{ secrets.PROJECT_ID }}

      # Step 3: Set up MongoDB Shell (mongosh)
      - name: Setup MongoDB Tools
        uses: boly38/action-mongo-tools@stable
        with:
          mongosh_version: '2.1.5'

      # Step 4: Execute Query from File with Debugging
      - name: Execute Query from File
        run: |
          pwd  # Should be /home/runner/work/<repo>/<repo>
          ls -la  # Should list query.js
          which mongosh  # Confirm mongosh is available
          mongosh --version  # Verify version
          mongosh "${{ secrets.MONGO_URI }}" query.js
